### ISSUE TITLE
Cannot train on multiple gpu's

### ISSUE THREAD

**Issue by x12901** [vijaydwivedi75/Custom-Mask-RCNN_TF#3]
I try to train on multiple gpu's and it seems to run out of memory. Modifying main.py to only train on cpu will run. I don't know how to modify the program to train on multiple gpu's?
windows10
tensorflow 1.15.0
tensorflow models branch r1.12
gpu 1080ti * 4
[https://github.com/x12901/error](url)

**Comment by x12901** [comment]
> I try to train on multiple gpu's and it seems to run out of memory. Modifying main.py to only train on cpu will run. I don't know how to modify the program to train on multiple gpu's?
> windows10
> tensorflow 1.15.0
> tensorflow models branch r1.12
> gpu 1080ti * 4
> [https://github.com/x12901/error](url)

I solved this problem using the new version of model_main.py

**Comment by x12901** [comment]
> > I try to train on multiple gpu's and it seems to run out of memory. Modifying main.py to only train on cpu will run. I don't know how to modify the program to train on multiple gpu's?
> > windows10
> > tensorflow 1.15.0
> > tensorflow models branch r1.12
> > gpu 1080ti * 4
> > [https://github.com/x12901/error](url)
> 
> I solved this problem using the new version of model_main.py

The new program will still run out of memory.
